{
  "hash": "7a83df8190a1a3cca63f9803d4db2f18",
  "result": {
    "markdown": "---\ntitle: Misinformed conclusions\ndescription: \"caveat lector\"\nauthor:\n  - name: Jay Brophy\n    url: https://brophyj.github.io/\n    orcid: 0000-0001-8049-6875\n    affiliation: McGill University Dept Medince, Epidemiology & Biostatistics\n    affiliation-url: https://mcgill.ca \ntags: []\ncategories: [Evidence based medicine, Bayesian stats]\nimage: featured.jpg\nformat: \n  html:\n    fig-height: 1\ncitation: \n  url: https://brophyj.github.io/posts/2023-04-15-my-blog-post/ \ndate: 2023-04-15T14:39:55-05:00\nlastmod: 2023-04-15T14:39:55-05:00\nfeatured: true\ndraft: false\n# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.\nprojects: []\ncode-fold: true\neditor_options: \n  markdown: \n    wrap: sentence\n---\n\n\n## Likely unintentional (but misinformation nevertheless)\n\nIn three papers that I read this week, I believe that each suffers from misinterpretations in their conclusions[@RN6772][@RN6776][@RN6773].\n\n## Example 1\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](featured1.png){fig-align='center' width=75%}\n:::\n:::\n\n\nIn the first paper[@RN6772], the authors conclude\n\n> \"In Medicare patients with pure native AR, TAVR with the current commercially available transcatheter valves has comparable short-term outcomes. Although long-term outcomes were inferior to SAVR, the possibility of residual confounding, biasing long-term outcomes, given older and frailer TAVR patients, cannot be excluded.\"\n\nWhile acknowledging that TAVR was associated with higher unadjusted (HR, 1.90; 95% CI, 1.59-2.26; P \\< .001) and adjusted risk of all-cause mortality compared with SAVR (adjusted HR, 1.41; 95% CI, 1.03-1.93; P = .02) with long term follow-up (which may indeed be at least partially explained by residual confounding), the authors interpret the results as being comparable for the two techniques at one year. They report one year propensity score adjusted mortality as 5.7% and 6.9% mortality in the TAVR and SAVR patient, respectively (p=0.3).\n\nDrawing conclusions based on p values is known to be dangerous and a proposed, albeit perhaps minor, improvement is to use confidence intervals[@RN5420]. The following shows the risk difference with the 95% CI for the two mortality outcomes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(c(round(c(.057*9880,.069*1147))),c(9980,1147))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(round(c(0.057 * 9880, 0.069 * 1147))) out of c(9980, 1147)\nX-squared = 2.7, df = 1, p-value = 0.1\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.028287  0.003362\nsample estimates:\n prop 1  prop 2 \n0.05641 0.06888 \n```\n:::\n:::\n\n\nThe implies that even ignoring any biases, concluding that the two approaches have similar short term outcomes is only reasonable if one believes that a possible 2.8% absolute mortality reduction with SAVR from sampling variation alone is not clinically important. Others might consider that the conclusion is another example of conflating **absence of evidence with evidence of absence** and that additional data is required before drawing firm conclusions. This underscores the problem with dichotomized p values and risk ratios (as opposed to risk differences) as decision making tools.\n\n## Example 2\n\nA NEJM article[@RN6776] reported P that\n\n> \"the prophylactic use of tranexamic acid during cesarean delivery did not lead to a significantly lower risk of a composite outcome of maternal death or blood transfusion than placebo\" (RR 0.89; 95% CI 0.74 to 1.07; P=0.19 for the primary outcome).\"\n\nThese results could also be expressed as risk differences and attributable risks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmat1 <- matrix(c(233,201,5238,5328), nrow = 2, \n              dimnames = list(c(\"placebo\",\"tranexamic acid\"),c(\"Outcome +\",\"Outcome -\")))\nmat1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                Outcome + Outcome -\nplacebo               233      5238\ntranexamic acid       201      5328\n```\n:::\n\n```{.r .cell-code}\nepiR::epi.2by2(mat1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Outcome +    Outcome -      Total                 Inc risk *\nExposed +          233         5238       5471        4.26 (3.74 to 4.83)\nExposed -          201         5328       5529        3.64 (3.16 to 4.16)\nTotal              434        10566      11000        3.95 (3.59 to 4.33)\n\nPoint estimates and 95% CIs:\n-------------------------------------------------------------------\nInc risk ratio                                 1.17 (0.97, 1.41)\nOdds ratio                                     1.18 (0.97, 1.43)\nAttrib risk in the exposed *                   0.62 (-0.10, 1.35)\nAttrib fraction in the exposed (%)            14.64 (-2.70, 29.05)\nAttrib risk in the population *                0.31 (-0.30, 0.92)\nAttrib fraction in the population (%)         7.86 (-1.76, 16.57)\n-------------------------------------------------------------------\nUncorrected chi2 test that OR = 1: chi2(1) = 2.820 Pr>chi2 = 0.093\nFisher exact test that OR = 1: Pr>chi2 = 0.096\n Wald confidence limits\n CI: confidence interval\n * Outcomes per 100 population units \n```\n:::\n:::\n\n\nThe risk difference is 6 fewer outcomes /1000 treated (95% CI-13.5, 1.0) and the attributable fraction is 14.6% (95% CI -2.70, 29.05) of outcomes being eliminated by treatment.  While these measures do not reach statistical significance, they may provide some additional insights into the trial's interpretation as the associated sampling variations suggest an effect size as large as 13 fewer outcomes / 1000 treated and an attributable fraction as large as 29% have not been eliminated. If one believes these potential measures are of clinical importance, then continuing research with this agent may be indicated.\n\n## Example 3\n\nThe third paper is entitled \" Effect of a Run-In Period on Estimated Treatment Effects in Cardiovascular Randomized Clinical Trials: A Meta-Analytic Review\"[@RN6773] and the authors concluded \"The use of a run-in period was not associated with a difference in the magnitude of treatment effect among cardiovascular prevention trials\".\n\nI found this result to be a priori very surprising. However without the raw data it is difficult to completely reproduce and assess what the authors have done. Nevertheless working with the aggregate data from the last column in Figure 1, I have performed a Bayesian analysis, with a vaguely informative prior such that the results are completely dominated by the published data.\n\nThe posterior probability is displayed below.\n\n\n::: {.cell hash='index_cache/html/brms_e3c1063390843577f44816716b2c0165'}\n::: {.cell-output-display}\n![](index_files/figure-html/brms-1.png){width=60%}\n:::\n:::\n\n\n### ggplot version\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nBased on this analysis, the probability that run-in trials has a larger treatment effect than non-run-in trials was 99 %. There was an 79 % probability that the effect size was at least 5% greater in the run-in trials. While this effect is not large, it is more in keeping with face validity that would suggest that run-in trials, by excluding non-compilers and those developing side effects, would be expected to yield a larger effect size than a comparable trial without a run-in period. \\newpage\n\n## References\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}