---
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">


## Summary
      
 A quick summary of the project can be found [here](files/summary.pdf)


## Is the study ethical?
      
**YES** is the short answer.     
While the CCS guidelines (2012) recommend ticagrelor over clopidogrel,    
* US guidelines (2012) listed both drugs as being comparable but did mention an increased concern about bleeding with ticagrelor    
* More recently, the ESC in their 2018 Revasculation Guidelines state that both ticagrelor and clopidogrel are appropriate as antiplatelet agents and make no recommendation for one over the other    
* This trial has also been judged ethical by CIHR (funding agency) and the McGill University Hospital Center Research Ethics Board     
* Members of the CUSM/MUHC Division of Cardiology have judged that the necessary clinical equipoise exists to perform this study     
* At the time of ticagrelor approval, the FDA recommended a confirmation study in North American patients but that study has never been done, **until now!** 


## As a MD what do I have to do?
        
* We ask you simply to continue the DAPT initiated during your patient's MUHC stay   
* You decide on the duration of the therapy according to your usual criteria. Generally, DAPT is continued for 12 months unless there are special circumstances     
* Obviously if you feel strongly that a different DAPT is in your patient's best interest then you are free to make the change.      

## As a patient what do I have to do?       

The success of this, and any study, depends on patients staying on their assigned therapy. Please continue your therapy until your treating MD tells you otherwise. 