---
title: ""
engine: knitr
freeze: false
cv:
  pdf: "upload/JGH.pdf"
muhc:
  pdf: "upload/MUHC_DAPT1.pdf"
tau:
  pdf: "upload/TAU.pdf"
med:
  pdf: "upload/MA.pdf"
quarto_html:
  revealjs: "upload/cardiology1_nov2024.html"
cardio2025:
  pdf: "upload/cardio2025.pdf"
IM2025:
  pdf: "upload/IM2025.pdf"
---

<p style="font-size: xx-large; background-color: crimson; display: inline-block;color: #f1f1f1; font-weight: bold">

Presentations <iconify-icon icon="et:presentation"></iconify-icon>

</p>

# 2025

-   **Meta-analysis to meta-cognition - The Bayesian Highway in Internal Medicine**\
    McGill University Hospital Center, Department of Medicine, Cardiology Grand Rounds, Oct 25 2025\
    **Summary** - Meta-analysis is powerful, but not infallible technique. Many of its limitations are tied to the traditional frequentist framework in which it is most often performed. This talk is an updated version of the previous talk in Sept 2025 but addresses new examples including the principles of Bayesian meta-analysis as applied to extended thrombolysis for ischemic stroke and dexmedetomidine for post-operative delirium.

<p class="text-center">
<a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$IM2025$pdf`" target="_blank">
  <i class="fa-solid fa-file-arrow-down"></i> Slides (opens in new tab)
</a>
</p>

-   **Meta-analysis to meta-cognition - The Bayesian Highway in Cardiology**\
    McGill University Hospital Center, Department of Medicine, Cardiology Grand Rounds, Sept 11 2025\
    **Summary** - Meta-analysis is powerful, but not infallible technique. Many of its limitations are tied to the traditional frequentist framework in which it is most often performed. A Bayesian approach to meta-analysis can address many of these limitations, and ofers a more intuitive and flexible framework for evidence synthesis. This talk will review the principles of Bayesian meta-analysis, its advantages over traditional approaches, and its potential to enhance clinical decision-making in cardiology.


<p class="text-center">
<a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$cardio2025$pdf`" target="_blank">
  <i class="fa-solid fa-file-arrow-down"></i> Slides (opens in new tab)
</a>
</p>

<p class="text-center">
<a class="btn btn-primary btn-lg cv-download" href="https://www.youtube.com/watch?v=IL_w5293Hz0" target="_blank">
  <i class="fa-solid fa-file-arrow-down"></i> Video (opens in new tab)
</a>
</p>

-   **Doctoral seminar - Epidemiology 706**\
    McGill University, Department of Epidemiology, Winter 2025\
    **Summary** - 706 is a PhD-level seminar aimed at providing space for students to engage with over-arching concepts critical to the theory and practice of epidemiology, as well to explore recent controversies and debates in the field. The purpose of this course to reinforce your formal methodological coursework by making space to develop and sharpen your critical thinking skills.

<p class="text-center">

<a class="btn btn-primary btn-lg cv-download" href="upload/epib706.html" target="_blank"> <i class="fa-solid fa-file-arrow-down"></i>Syllabus (opens in new tab) </a>

</p>


-   **Statistics, uncertainty and the physician**\
    McGill University Health Centre, Department of Medicine Grand Rounds, Jan 7 2025\
    **Summary** - Some not so random reflections on statistical concepts tailored for general internists and cardiologists

<p class="text-center">

<a class="btn btn-primary btn-lg cv-download" href="upload/Jan7Rounds.html" target="_blank"> <i class="fa-solid fa-file-arrow-down"></i>View Presentation (opens in new tab) </a>

</p>

# 2024

-   **Hierarchical models**\
    McGill University, Department of Epidemiology, Nov 2024\
    **Summary** - Lecture to PhD students (EPIB704) on the benefits of and procedures for performing hierarchical modelling

<p class="text-center">

<a class="btn btn-primary btn-lg cv-download" href="upload/hier_lecture.html" target="_blank"> <i class="fa-solid fa-file-arrow-down"></i>View Presentation (opens in new tab) </a>

</p>

-   **An Introduction to Statistics for Cardiologists**\
    McGill University Health Centre, Division of Cardiology Grand Rounds, Nov 2024\
    **Summary** - Some not so random reflections on statistical concepts tailored for cardiologists

<p class="text-center">

<a class="btn btn-primary btn-lg cv-download" href="upload/cardiology1_nov2024.html" target="_blank"> <i class="fa-solid fa-file-arrow-down"></i>View Presentation (opens in new tab) </a>

</p>

#  2023

<!-- -->

-   **An introduction to systematic reviews and (sometimes) meta-analysis**\
    McGill University Medical School Lecture, Montreal QC, Nov 30 2023\
    **Summary** - Review of basic systematic review and meta-analysis techniques for 2nd year medical students

<p class="text-center">

<a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$med$pdf`" target="_blank"> <i class="fa-solid fa-file-arrow-down"></i> Download slides </a>

</p>

<div>

<iframe src="`r rmarkdown::metadata$med$pdf`" style="border: 0.5px">

</iframe>

</div>

-   **A Bayesian view of contemporary randomized clinical trials – New reflections from an old lens**\
    Montreal Jewish General Hospital, Clinical Epidemiology Rounds, Montreal QC, Nov 15 2023\
    **Summary** - Review of Bayesian principles and their advantages highlighted by re-analyses of several randomized trials recently published in the NEJM

<p class="text-center">

<a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$cv$pdf`" target="_blank"> <i class="fa-solid fa-file-arrow-down"></i> Download slides </a>

</p>

<div>

<iframe src="`r rmarkdown::metadata$cv$pdf`" style="border: 0.5px">

</iframe>

</div>

-   **Dual antiplatelet therapy (DAPT) in 2023 - The McGill Experience**\
    McGill University Health Centre, Department of Medicine Grand Rounds, Montreal QC, Oct 30 2023\
    **Summary** - Review of three research studies performed at McGill - i) Bayesian network meta-analysis ii) pharmacoepidemiology study iii) cluster randomized registry trial

[**YouTube presentation**](https://www.youtube.com/watch?v=0OqPSr8Q208)

<p class="text-center">

<a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$muhc$pdf`" target="_blank"> <i class="fa-solid fa-file-arrow-down"></i> Download slides </a>

</p>

<div>

<iframe src="`r rmarkdown::metadata$muhc$pdf`" style="border: 0.5px">

</iframe>

</div>

-   **L'experience de l’unité d'évaluation des technologies (TAU) de CUSM - Regarder dans le rétroviseur pour mieux voir l’avenir** (The Experience of McGill's Technology Assessment Unit - Looking back to better see the future)\
    Symposium en évaluation des technologies et modes d’intervention en santé, Centre hospitalier de l’Université de Montréal (CHUM), Montreal QC, Oct 19 2023\
    **Summary** - Review of TAU's lessons learned, the first hospital based technology assessment unit

<p class="text-center">

<a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$tau$pdf`" target="_blank"> <i class="fa-solid fa-file-arrow-down"></i> Download slides (english) </a>

</p>

<div>

<iframe src="`r rmarkdown::metadata$tau$pdf`" style="border: 0.5px">

</iframe>

</div>
