{
  "hash": "d75b389558c106994d33a1af404b4ac9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Collider stratification\"\ndescription: \"Smoking protective for repeat revascularizations!???\"\nauthor:\n  - name: Jay Brophy\n    url: https://brophyj.github.io/\n    orcid: 0000-0001-8049-6875\n    affiliation: McGill University Dept Medince, Epidemiology & Biostatistics\n    affiliation-url: https://mcgill.ca \ntags: []\ncategories: [Scientific review, statistical methods]\nimage: preview-image.jpg\ncitation: \n  url: https://brophyj.com/posts/2025-11-26-my-blog-post/ \ndate: 2025-11-26T14:39:55-05:00\nlastmod: 2025-11-26T14:39:55-05:00\nfeatured: true\ndraft: false\n# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.\nprojects: []\ncode-fold: true\neditor_options: \n  markdown: \n    wrap: sentence\nbibliography: [bib.bib]\nbiblio-style: apalike\n---\n\n## A recent study\n\nSmoking is a well-established risk factor for endothelial damage, increased thrombogenesis, and adverse cariac events including the need for revascularizations. Yet Presch[@RN7087] reports paradoxically that smoking is associated with a lower risk of repeat revascularization.  It is hard to conceive why the endothelium would react differently if it had experienced a previous revascularization procedure.  More likely the observed protective role is due to collider risk stratification bias which has successfully explained the obesity, aspirin, and previous smoking paradoxes among many others[@RN6478][@RN7085][@RN7086]. \n\n## Background on collider risk stratification\n\nConsider a simplified data generating mechanism (DGM) for the development of coronary artery disease, reequiring revascularizaion, in the general population. Let's assume that causal factors are smoking and all other risk factors are combined into one other variable. The causal diagram is therefore as follows\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(ggdag)\n\nrevasc_dag <- collider_triangle(\n  x = \"Smoking\",\n  y = \"Other (unmeasured) risk factors\",\n  m = \"Revascularization\"\n)\n\nggdag(revasc_dag, text = FALSE, use_labels = \"label\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nHere for the general population we have assumed that smoking and the other risk factors are independent (no connecting arrow). But look what happens if we select (stratify or condition) on receiving a revascularization procedure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncollid <- ggdag_dseparated(revasc_dag,\n                 controlling_for = \"m\",\n                 text = FALSE, use_labels = \"label\"\n)\ncollid\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggsave(\"collider.png\", collid, width = 5, height = 4)\n```\n:::\n\n\nThis has induced a relationship between smoking and the other risk factors. If the patient is a non-smoker then they must have other (unmeasured) risk factors since they required an initial revascularization procedure. Therefore among those have received an initial revascularization procedure, the non-smokers will, in the expectation, be sicker than the smokers and these higher levels of other (unmeasured) risk factors are strong predictors for future revascularization. From the oppositer perspective, the smokers will look to be protected by their smoking even though the underlying data generating mechanism (an increased risk due to smoking) has not been altered. \\\n\nTo demonstrate this let's perform a simulation study.  \n\n\n\n\n\n## Simulation study\n\nTo concretely demonstrate this spurious association we will perform a numerical simulation. Assume 10,000 individuals with a 30% smoking prevalence and a normal disribution of the other (unmeasured) risk factors, (U). The probability of receiving a percutaneous coronary intervention (PCI) is modeled using a logistic model where both smoking and U increase the chance of PCI. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set a seed for reproducibility\noptions(digits = 2)\n# ---------------------------\n# Chunk 1: Generate Full Population Data\n# ---------------------------\nset.seed(123)\n\n# Population parameters for outcome data generating model (DGM):\nn <- 100000               # Total individuals\np_smoking <- 0.3          # Smoking prevalence\nbeta_smoking <- 0.3       # True effect of smoking (log-odds); OR ≈ exp(0.3) ≈ 1.35\nbeta_U <- 1               # Effect of U on outcome\nintercept_outcome <- -2   # Outcome intercept for repeat PCI\n\n# Simulate predictors:\nsmoking <- rbinom(n, 1, p_smoking)\nU <- rnorm(n)             # Unobserved risk factor\n\n# Generate outcome (repeat PCI) for full population using the same DGM:\nlogit_outcome <- intercept_outcome + beta_smoking * smoking + beta_U * U\np_outcome <- exp(logit_outcome) / (1 + exp(logit_outcome))\nrepeat_PCI <- rbinom(n, 1, p_outcome)\n\n# ---------------------------\n# Chunk 2: Generate PCI via a Deterministic (Threshold) Rule\n# ---------------------------\n# Define PCI as follows:\n#   For smokers (smoking == 1): PCI = 1 if U > 0.5.\n#   For non-smokers (smoking == 0): PCI = 1 if U > 1.5.\nPCI <- ifelse(smoking == 1, as.numeric(U > 0.5), as.numeric(U > 1.1))\n\n# Combine into one data frame:\ndf <- data.frame(smoking, U, PCI, repeat_PCI)\n\n# ---------------------------\n# Chunk 3: Full Population Analysis\n# ---------------------------\n# Fit a logistic regression for repeat PCI on smoking (ignoring U) in the full population:\nmodel_full <- glm(repeat_PCI ~ smoking, data = df, family = binomial)\ntemp <- summary(model_full)\nsummary(model_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = repeat_PCI ~ smoking, family = binomial, data = df)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.6896     0.0104  -162.2   <2e-16 ***\nsmoking       0.2717     0.0179    15.2   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 90396  on 99999  degrees of freedom\nResidual deviance: 90171  on 99998  degrees of freedom\nAIC: 90175\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\n# exp(coef(model_full))  # Display odds ratios\n\nsmoke_est <- exp(temp$coefficients[2,1])\nsmoke_CI <-exp(temp$coefficients[2,1] + c(-1,1)*1.96*temp$coefficients[2,2])\n```\n:::\n\n\nThis confirms the DGM is performing as expected with an increased smoking risk = 1.31 (exp(0.2717)) with 95% CI (1.27 to 1.36)  Note in this illustrative case, a deterministic model for PCI with non-smokers having higher (non-measured) risk factors has been used. In the real world this world, a probabilistic mnodel would be employed\\\n \\\nNow let's see the effect of smoking on the study population, i.e. only those that underwent an initial revascularization procedure. Here we assume the same DGM for a future repeat PCI as initially applied to the general population i.e. smoking risk = 1.3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ---------------------------\n# Chunk 4: Analysis in PCI-Selected Sample\n# ---------------------------\n# Restrict the data to individuals with PCI == 1:\ndata_PCI <- subset(df, PCI == 1)\n\n# Fit the logistic regression model for repeat PCI on smoking in the PCI-selected sample:\nmodel_PCI <- glm(repeat_PCI ~ smoking, data = data_PCI, family = binomial)\ntemp1 <- summary(model_PCI)\nsummary(model_PCI)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = repeat_PCI ~ smoking, family = binomial, data = data_PCI)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -0.3680     0.0206  -17.84  < 2e-16 ***\nsmoking      -0.1367     0.0298   -4.58  4.6e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 25340  on 18905  degrees of freedom\nResidual deviance: 25319  on 18904  degrees of freedom\nAIC: 25323\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\n# exp(coef(model_PCI))  # Display odds ratios in the selected sample\n\n\nsmoke_est_sample <- exp(temp1$coefficients[2,1])\nsmoke_CI_sample <- exp(temp1$coefficients[2,1] + c(-1,1)*1.96*temp1$coefficients[2,2])\n```\n:::\n\n\nUsing the exact same data generating mechanism, with increased risk with smoking (RR =1.3) for a repeat revascularization procedure, the smoking parameter in the study sample has been reduced to 0.87 (exp(-.1367)) with 95% CI (0.82 to 0.92) due to collider risk stratification bias \\    \n\nThis simulation illustrates collider-stratification bias: even though the true effect of smoking in the full population is harmful (OR ≈ 1.35) and remains harmful for a repeat procedure, when you condition on PCI smoking looks protective simply because the non-smokers are otherwise at increased risk due to the spurious induced associated between the other (unmeasured) risk factors and smoking. \n\n## Visual interpretation\n\nThis spurious results can be shown visually as follows. The following two density plots show the distribution of the unobserved risk factor U in the full population (left plot) and in the PCI-selected sample (right plot). In both plots the distributions are stratified by smoking status (red = smokers, blue = non-smokers).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(patchwork)  # for side-by-side plots\n\n# Assume df and data_PCI already exist, with columns:\n#   U: unobserved risk factor\n#   smoking: 0/1\n#   PCI: 0/1\n#   repeat_PCI: outcome\n\n# Create a \"Group\" variable to label each dataset\ndf$Group <- \"Full Population\"\ndata_PCI$Group <- \"PCI Selected\"\n\n# Plot 1: Full population\np1 <- ggplot(filter(df, Group == \"Full Population\"),\n             aes(x = U, fill = factor(smoking))) +\n  geom_density(alpha = 0.5) +\n  coord_cartesian(xlim = c(-3, 3)) +  # adjust as needed\n  labs(\n    title = \"Distribution of U in the Full Population\",\n    x = \"U (Unobserved Risk Factor)\",\n    y = \"Density\",\n    fill = \"Smoking\\n(0=No,1=Yes)\"\n  ) +\n  theme_minimal()\n\n# Plot 2: PCI-selected, x-axis starting at 0\np2 <- ggplot(filter(data_PCI, Group == \"PCI Selected\"),\n             aes(x = U, fill = factor(smoking))) +\n  geom_density(alpha = 0.5) +\n  coord_cartesian(xlim = c(0, NA)) +  # start x-axis at 0\n  labs(\n    title = \"Distribution of U in PCI-Selected Sample\",\n    x = \"U (Unobserved Risk Factor)\",\n    y = \"Density\",\n    fill = \"Smoking\\n(0=No,1=Yes)\"\n  ) +\n  theme_minimal()\n\n# Display plots side by side\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nFull Population (left plot) shows how the unobserved risk factor \nU is distributed equally among both smokers (red) and non-smokers (blue) in the entire dataset. In the study sample, PCI-selected sample (right plot) because of the selection mechanism you can more clearly see that non-smokers in the PCI sample have U-values > the values in smokers. Hence the false impression that smoking is protective.\n\n\n\n## Conclusion\n\nDespite a data generating mechanism that assigned an increased risk with smoking (HR = 1.36), this risk appears to be protective (HR 0.87 95% CI [0.82 to 0.92]) when the  population is conditioned on the performance of an initial revascularization (the collider)[@RN7088]. This reversal is a classic example of collider bias, where conditioning on a collider variable, influenced by both the exposure and an unmeasured confounder distorts the true effect.\n\n\n## References\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}